# production.yml
---
cors_origins: "http://{{ hostvars[inventory_hostname].ansible_host }},https://{{ domain_name }}"
certbot_domains:
  - "preview.{{ domain_name }}"
certbot_cert_name: "preview.{{ domain_name }}"
nginx_server_names: "preview.{{ domain_name }}"
