all:
  children:
    amazon_linux:
      children:
        production:
          hosts:
            prod:
              ansible_host: "{{ lookup('env', 'EC2_HOST') }}"
        staging:
          hosts:
            staging_host:
              ansible_host: "{{ lookup('env', 'STAGING_EC2_HOST') }}"
    ubuntu:
      children:
        production:
          hosts:
            prod:
              ansible_host: "{{ lookup('env', 'EC2_UBUNTU_HOST') }}"
        staging:
          hosts:
            staging_host:
              ansible_host: "{{ lookup('env', 'STAGING_EC2_UBUNTU_HOST') }}"