all:
  children:
    amazon_linux:
      children:
        production:
          hosts:
            prod:
              ansible_host: "{{ lookup('env', 'EC2_HOST') }}" #18.214.118.179
        staging:
          hosts:
            staging_host:
              ansible_host: "{{ lookup('env', 'STAGING_EC2_HOST') }}" #3.137.143.9