all:
  children:
    staging:
      hosts:
        staging-amazon:
          ansible_host: "{{ lookup('env', 'STAGING_EC2_HOST') }}"
        staging-ubuntu:
          ansible_host: "{{ lookup('env', 'STAGING_EC2_UBUNTU_HOST') }}"
    production:
      hosts:
        prod-amazon:
          ansible_host: "{{ lookup('env', 'EC2_HOST') }}"
        prod-ubuntu:
          ansible_host: "{{ lookup('env', 'EC2_UBUNTU_HOST') }}"
    amazon_linux:
      hosts:
        staging-amazon:
        prod-amazon:
    ubuntu:
      hosts:
        staging-ubuntu:
        prod-ubuntu: