name: Deploy FastAPI Application

on:
  push:
    branches:
      - main
      - staging

env:
  VITE_API_URL: /api

jobs:
  deploy-production:
    if: github.ref_name == 'main'
    runs-on: [self-hosted, production]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js & Build Frontend
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          cd frontend
          npm install
          npm run build

      - name: Set deployment target
        run: |
          echo "DEPLOY_HOST=${{ secrets.EC2_HOST }}" >> "$GITHUB_ENV"
          echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> "$GITHUB_ENV"
          echo "ANSIBLE_GROUP=production" >> "$GITHUB_ENV"

      - name: Deploy files via rsync
        run: |
          rsync -av --delete \
            --exclude '.git*' \
            --exclude 'venv/' \
            --exclude '__pycache__/' \
            --exclude '.env' \
            --exclude 'node_modules/' \
            ./ ${{ secrets.DEPLOY_PATH }}
      
      - name: Grant frontend permissions to user
        run: |
          chmod 755 /home/${{ secrets.EC2_USER }}
          chmod 755 ${{ secrets.DEPLOY_PATH }}/frontend/dist

      - name: Save Ansible vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > temp_ansible_pass.txt
          chmod 600 temp_ansible_pass.txt

      - name: Install Ansible
        working-directory: ansible
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          sudo dnf install -y python3-pip
          python3 -m pip install --user ansible

          ansible-galaxy install -r requirements.yml -p roles --timeout 120
          ansible-galaxy collection install -r requirements.yml --force --timeout 120

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export ANSIBLE_ROLES_PATH=$(pwd)/roles
          export ANSIBLE_HOST_KEY_CHECKING=False
          export EC2_HOST="${{ env.EC2_HOST }}"
          
          ansible-playbook playbooks/site.yml   \
          -i inventory/hosts.yml   \
          --limit 'amazon_linux:&${{ env.ANSIBLE_GROUP }}'   \
          -e "target_group=${{ env.ANSIBLE_GROUP }}"   \
          -c local \
          --vault-password-file $GITHUB_WORKSPACE/temp_ansible_pass.txt

      - name: Clean up secrets
        if: always()
        run: |
          rm -f $GITHUB_WORKSPACE/temp_ansible_pass.txt

  deploy-staging:
    if: github.ref_name == 'staging'
    runs-on: [self-hosted, staging]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js & Build Frontend
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          cd frontend
          npm install
          npm run build

      - name: Set deployment target
        run: |
          echo "STAGING_EC2_HOST=${{ secrets.STAGING_EC2_HOST }}" >> "$GITHUB_ENV"
          echo "EC2_HOST=${{ secrets.STAGING_EC2_HOST }}" >> "$GITHUB_ENV"
          echo "ANSIBLE_GROUP=staging" >> "$GITHUB_ENV"

      - name: Deploy files via rsync
        run: |
          rsync -av --delete \
            --exclude '.git*' \
            --exclude 'venv/' \
            --exclude '__pycache__/' \
            --exclude '.env' \
            --exclude 'node_modules/' \
            ./ ${{ secrets.DEPLOY_PATH }}
      
      - name: Grant frontend permissions to user
        run: |
          chmod 755 /home/${{ secrets.EC2_USER }}
          chmod 755 ${{ secrets.DEPLOY_PATH }}/frontend/dist

      - name: Save Ansible vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > temp_ansible_pass.txt
          chmod 600 temp_ansible_pass.txt

      - name: Install Ansible
        working-directory: ansible
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          sudo dnf install -y python3-pip
          python3 -m pip install --user ansible

          ansible-galaxy install -r requirements.yml -p roles --timeout 120
          ansible-galaxy collection install -r requirements.yml --force --timeout 120

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export ANSIBLE_ROLES_PATH=$(pwd)/roles
          export ANSIBLE_HOST_KEY_CHECKING=False
          export STAGING_EC2_HOST="${{ env.STAGING_EC2_HOST }}"

          ansible-playbook playbooks/site.yml   \
          -i inventory/hosts.yml   \
          --limit 'amazon_linux:&${{ env.ANSIBLE_GROUP }}'   \
          -e "target_group=${{ env.ANSIBLE_GROUP }}"   \
          -c local \
          --vault-password-file $GITHUB_WORKSPACE/temp_ansible_pass.txt

      - name: Clean up secrets
        if: always()
        run: |
          rm -f $GITHUB_WORKSPACE/temp_ansible_pass.txt
